version: '3'
services:
  web:
    image: client-portal
    build:
      context: .
      dockerfile: Dockerfile-dev
    networks:
      - backend
    ports:
      - "3101:3000"
    volumes:
      - ./:/usr/src/app

networks:
  backend:
    driver: bridge