version: '3'
services:
  web:
    image: 1cec0ld-frontend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "3110:443"
    volumes:
      - ./:/usr/src/app

networks:
  backend:
    driver: bridge